/**
 * Compile the plugin to a standalone native binary via
 * `bun build --compile`, drop it into the .sdPlugin/bin folder,
 * and (on Windows) optionally hot-reload Stream Deck so the new
 * binary takes effect without a manual quit/relaunch.
 *
 * Stream Deck holds an exclusive lock on the running plugin's .exe,
 * so a build while the plugin is live would fail with "could not
 * open file for writing". The reload dance is:
 *
 *   1. Kill Stream Deck if it's running (releases the .exe lock)
 *   2. Compile the new binary in place
 *   3. Relaunch Stream Deck (Start-Process, detached)
 *
 * This is the default because we almost always want it. Pass
 * `--no-reload` to skip the kill/relaunch (useful for CI or when
 * chained with `install:dev --restart`).
 *
 * Usage:
 *   bun run build                 # kill → compile → relaunch
 *   bun run build --no-reload     # compile only
 *   bun run build:win / :mac      # explicit target
 */

import { $ } from "bun";
import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { platform } from "node:os";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const SDPLUGIN = resolve(ROOT, "io.github.anthonybaldwin.UsageButtons.sdPlugin");
const BIN_DIR = resolve(SDPLUGIN, "bin");
const ENTRY = resolve(ROOT, "src/plugin.ts");

interface Target {
  name: string;
  bunTarget: string; // --target value
  outfile: string;   // relative to BIN_DIR
}

/**
 * Single-binary targets (Windows only for now). The `mac` target
 * is special — it builds TWO binaries (arm64 + x64) plus a shell
 * wrapper that dispatches at runtime, so it isn't in this map.
 */
const TARGETS: Record<string, Target> = {
  win: {
    name: "Windows x64",
    bunTarget: "bun-windows-x64",
    outfile: "plugin-win.exe",
  },
};

/**
 * macOS targets — both Apple Silicon (arm64) and Intel (x64).
 * Stream Deck's manifest only has a single CodePathMac, so the
 * wrapper below picks the right binary at launch time via
 * `uname -m`. No Rosetta, no cross-platform compromises.
 */
const MAC_TARGETS: Target[] = [
  {
    name: "macOS Apple Silicon (arm64)",
    bunTarget: "bun-darwin-arm64",
    outfile: "plugin-mac-arm64",
  },
  {
    name: "macOS Intel (x64)",
    bunTarget: "bun-darwin-x64",
    outfile: "plugin-mac-x64",
  },
];

/**
 * Arch-dispatch shell wrapper that Stream Deck launches via
 * `CodePathMac: "bin/plugin-mac"`. Native on every mac — no
 * Rosetta fallback.
 */
const MAC_WRAPPER_SCRIPT = `#!/bin/sh
# UsageButtons Stream Deck plugin — arch-dispatch wrapper.
# Generated by scripts/build.ts. Do not edit by hand.
#
# Stream Deck launches this file via CodePathMac. We detect the
# CPU architecture at runtime and exec the matching
# \`bun build --compile\` output. The args Stream Deck passes
# (-port, -pluginUUID, -registerEvent, -info) flow straight
# through via "$@".
set -e
dir="$(cd "$(dirname "$0")" && pwd)"
case "$(uname -m)" in
  arm64|aarch64)
    exec "$dir/plugin-mac-arm64" "$@"
    ;;
  x86_64)
    exec "$dir/plugin-mac-x64" "$@"
    ;;
  *)
    echo "UsageButtons: unsupported macOS arch: $(uname -m)" >&2
    exit 1
    ;;
esac
`;

/**
 * Resolve the default target key from the current host platform.
 * "win" on Windows hosts, "mac" on darwin hosts (which triggers
 * the dual-arch macOS build path below).
 */
function currentTargetKey(): "win" | "mac" {
  if (process.platform === "win32") return "win";
  if (process.platform === "darwin") return "mac";
  throw new Error(`unsupported host platform: ${process.platform}`);
}

function log(line: string): void {
  // eslint-disable-next-line no-console
  console.log(line);
}

async function isStreamDeckRunning(): Promise<boolean> {
  if (platform() === "win32") {
    const res = Bun.spawnSync({
      cmd: ["tasklist", "/FI", "IMAGENAME eq StreamDeck.exe"],
      stdout: "pipe",
      stderr: "pipe",
    });
    return res.stdout.toString().toLowerCase().includes("streamdeck.exe");
  }
  const res = await $`pgrep -x "Stream Deck"`.nothrow().quiet().text();
  return res.trim().length > 0;
}

async function killStreamDeck(): Promise<void> {
  if (platform() === "win32") {
    Bun.spawnSync({
      cmd: ["taskkill", "/F", "/IM", "StreamDeck.exe"],
      stdout: "ignore",
      stderr: "ignore",
    });
  } else {
    await $`pkill -x "Stream Deck"`.nothrow().quiet();
  }
}

function startStreamDeck(): void {
  if (platform() === "win32") {
    const candidate = resolve(
      process.env["ProgramFiles"] ?? "C:/Program Files",
      "Elgato",
      "StreamDeck",
      "StreamDeck.exe",
    );
    if (!existsSync(candidate)) {
      log(`! could not locate ${candidate} — launch Stream Deck manually`);
      return;
    }
    // PowerShell Start-Process is the only reliable way to detach
    // a GUI child from our bun process without the Git Bash argv
    // mangling that blew up `cmd /c start ""` earlier in the session.
    Bun.spawnSync({
      cmd: [
        "powershell",
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-Command",
        `Start-Process -FilePath '${candidate.replace(/'/g, "''")}'`,
      ],
      stdout: "ignore",
      stderr: "ignore",
    });
  } else {
    // macOS
    Bun.spawnSync({ cmd: ["open", "-a", "Stream Deck"], stdout: "ignore", stderr: "ignore" });
  }
}

async function buildTarget(target: Target): Promise<void> {
  if (!existsSync(BIN_DIR)) mkdirSync(BIN_DIR, { recursive: true });
  const out = resolve(BIN_DIR, target.outfile);
  log(`→ compiling for ${target.name} → ${out}`);
  await $`bun build --compile --target=${target.bunTarget} --minify --sourcemap ${ENTRY} --outfile ${out}`;
  // Executable bit on POSIX hosts; no-op on Windows (bun build
  // --compile already marks the .exe as needed there). When
  // cross-compiling FROM Windows to Mac, the bit doesn't survive
  // the build so install:dev's Mac branch re-chmods after copying.
  try {
    chmodSync(out, 0o755);
  } catch {
    // ignore — install:dev will fix it on the target host
  }
  log(`✓ built ${target.outfile}`);
}

async function build(targetKey: "win" | "mac"): Promise<void> {
  if (targetKey === "win") {
    const target = TARGETS.win;
    if (!target) throw new Error("missing Windows target definition");
    await buildTarget(target);
    return;
  }

  // mac: build both arm64 and x64 binaries, then write the
  // arch-dispatch wrapper shell script that Stream Deck's
  // CodePathMac points at.
  for (const t of MAC_TARGETS) {
    await buildTarget(t);
  }

  const wrapperPath = resolve(BIN_DIR, "plugin-mac");
  writeFileSync(wrapperPath, MAC_WRAPPER_SCRIPT, { mode: 0o755 });
  try {
    chmodSync(wrapperPath, 0o755);
  } catch {
    // ignore
  }
  log(`✓ wrote arch-dispatch wrapper → ${wrapperPath}`);
  log(
    "  (Stream Deck launches this via CodePathMac; it execs the matching\n" +
    "   plugin-mac-arm64 / plugin-mac-x64 based on uname -m)",
  );
}

// Arg parsing: positional target + --no-reload flag
const rawArgs = process.argv.slice(2);
const noReload = rawArgs.includes("--no-reload");
const positional = rawArgs.find((a) => !a.startsWith("--"));
const key: "win" | "mac" =
  positional === "win" || positional === "mac"
    ? positional
    : currentTargetKey();

// Only kill/relaunch Stream Deck when building for the current
// platform. Cross-compiling (e.g. bun build:mac on Windows) doesn't
// touch the running plugin binary, so restarting is pointless.
const isNativeBuild = key === currentTargetKey();
const reload = !noReload && isNativeBuild;
const wasRunning = reload && (await isStreamDeckRunning());

if (wasRunning) {
  log("→ stopping Stream Deck to release the plugin .exe lock");
  await killStreamDeck();
}

log("→ typechecking");
await $`bun run typecheck`.quiet();
log("✓ typecheck passed");

await build(key);

if (reload && wasRunning) {
  log("→ relaunching Stream Deck");
  startStreamDeck();
  log("✓ Stream Deck relaunched; the new plugin binary will load on its own");
}
